### ISSUE TITLE
Ability to disable wind

### ISSUE THREAD

**Issue by EugZol** [ericpzh/MiniRealisticAirways#2]
Having constantly changing wind making all the schemes with waypoints pointless. Also, I'm not sure it's very realistic that over the course of couple of days in every airport in the world wind changes in a manner that would completely prevent landing/taking off in a particular direction, and then over the next couple of days the direction of horrible wind changes in 180º.

Hence, an ability to disable wind would be helpful!

**Comment by ericpzh** [comment]
Added `-disableWind` launch options to do this.
