### ISSUE TITLE
Disable TCAS

### ISSUE THREAD

**Issue by balintx** [ericpzh/MiniRealisticAirways#4]
Please consider adding an option to disable TCAS. It is not realistic (IRL planes won't make a 10k feet separation in case of a TCAS alert).

The greater problem is the collision alert of the game does not take the future Flight Level into consideration and it issues TCAS commands which violates the takeoff waypoint's orders of flight level.

In the below example I was experimenting with inbound traffic on Altitude Low, and making outbound traffic Altitude Medium ASAP on takeoff (WESt EXit and AROUnd West waypoints). This is working well for all aircrafts on takeoff, I have observed all of them maintaining Medium Altitude long before coming back to the runway line, so it should not interfere with any incoming traffic on Altitude Low.

However, due to any incoming traffic from time to time I get Traffic! warnings and sometimes TCAS orders outgoing aircraft to decrease altitude. As you can see both green outbound aircraft is on Altitude Low even though they exited through WESEX which should have put them on FL2 (Altitude Medium). Obviously one of them collided with an incoming aircraft. When there is no inbound traffic the outbound aircrafts always maintain FL2 without problem, so I suspect the problem is with TCAS.

![kép](https://github.com/user-attachments/assets/76645439-563f-4c77-82a5-0267fc63a467)

**Comment by ericpzh** [comment]
Added in new update.
